# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(890, 627)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(100, 100))
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.slider_delay1Coarse = QtGui.QSlider(self.centralwidget)
        self.slider_delay1Coarse.setGeometry(QtCore.QRect(37, 19, 21, 160))
        self.slider_delay1Coarse.setMaximum(127)
        self.slider_delay1Coarse.setPageStep(10)
        self.slider_delay1Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay1Coarse.setObjectName(_fromUtf8("slider_delay1Coarse"))
        self.slider_delay1Fine = QtGui.QSlider(self.centralwidget)
        self.slider_delay1Fine.setGeometry(QtCore.QRect(67, 19, 21, 160))
        self.slider_delay1Fine.setMaximum(127)
        self.slider_delay1Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay1Fine.setObjectName(_fromUtf8("slider_delay1Fine"))
        self.slider_feedback1 = QtGui.QSlider(self.centralwidget)
        self.slider_feedback1.setGeometry(QtCore.QRect(97, 19, 21, 160))
        self.slider_feedback1.setMaximum(127)
        self.slider_feedback1.setOrientation(QtCore.Qt.Vertical)
        self.slider_feedback1.setObjectName(_fromUtf8("slider_feedback1"))
        self.slider_delay2Coarse = QtGui.QSlider(self.centralwidget)
        self.slider_delay2Coarse.setGeometry(QtCore.QRect(127, 19, 21, 160))
        self.slider_delay2Coarse.setMaximum(126)
        self.slider_delay2Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay2Coarse.setObjectName(_fromUtf8("slider_delay2Coarse"))
        self.slider_delay2Fine = QtGui.QSlider(self.centralwidget)
        self.slider_delay2Fine.setGeometry(QtCore.QRect(157, 19, 21, 160))
        self.slider_delay2Fine.setMaximum(127)
        self.slider_delay2Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay2Fine.setObjectName(_fromUtf8("slider_delay2Fine"))
        self.slider_feedback2 = QtGui.QSlider(self.centralwidget)
        self.slider_feedback2.setGeometry(QtCore.QRect(187, 19, 21, 160))
        self.slider_feedback2.setMaximum(126)
        self.slider_feedback2.setOrientation(QtCore.Qt.Vertical)
        self.slider_feedback2.setObjectName(_fromUtf8("slider_feedback2"))
        self.slider_delay3Coarse = QtGui.QSlider(self.centralwidget)
        self.slider_delay3Coarse.setGeometry(QtCore.QRect(217, 19, 21, 160))
        self.slider_delay3Coarse.setMaximum(126)
        self.slider_delay3Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay3Coarse.setObjectName(_fromUtf8("slider_delay3Coarse"))
        self.label_delay1Coarse = QtGui.QLabel(self.centralwidget)
        self.label_delay1Coarse.setGeometry(QtCore.QRect(37, 179, 21, 17))
        self.label_delay1Coarse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay1Coarse.setObjectName(_fromUtf8("label_delay1Coarse"))
        self.label_delay1Fine = QtGui.QLabel(self.centralwidget)
        self.label_delay1Fine.setGeometry(QtCore.QRect(67, 179, 21, 17))
        self.label_delay1Fine.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay1Fine.setObjectName(_fromUtf8("label_delay1Fine"))
        self.label_feedback1 = QtGui.QLabel(self.centralwidget)
        self.label_feedback1.setGeometry(QtCore.QRect(97, 179, 21, 17))
        self.label_feedback1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback1.setObjectName(_fromUtf8("label_feedback1"))
        self.label_delay2Coarse = QtGui.QLabel(self.centralwidget)
        self.label_delay2Coarse.setGeometry(QtCore.QRect(127, 179, 21, 17))
        self.label_delay2Coarse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay2Coarse.setObjectName(_fromUtf8("label_delay2Coarse"))
        self.label_delay2Fine = QtGui.QLabel(self.centralwidget)
        self.label_delay2Fine.setGeometry(QtCore.QRect(157, 179, 21, 17))
        self.label_delay2Fine.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay2Fine.setObjectName(_fromUtf8("label_delay2Fine"))
        self.label_feedback2 = QtGui.QLabel(self.centralwidget)
        self.label_feedback2.setGeometry(QtCore.QRect(187, 179, 21, 17))
        self.label_feedback2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback2.setObjectName(_fromUtf8("label_feedback2"))
        self.label_delay3Coarse = QtGui.QLabel(self.centralwidget)
        self.label_delay3Coarse.setGeometry(QtCore.QRect(217, 179, 21, 17))
        self.label_delay3Coarse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay3Coarse.setObjectName(_fromUtf8("label_delay3Coarse"))
        self.spinbox_midiChannel = QtGui.QSpinBox(self.centralwidget)
        self.spinbox_midiChannel.setGeometry(QtCore.QRect(30, 550, 48, 27))
        self.spinbox_midiChannel.setMinimum(1)
        self.spinbox_midiChannel.setMaximum(16)
        self.spinbox_midiChannel.setObjectName(_fromUtf8("spinbox_midiChannel"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 200, 31, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 250, 56, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 230, 71, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(100, 200, 16, 17))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(140, 200, 31, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(130, 230, 71, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(140, 250, 56, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(190, 200, 16, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(227, 200, 31, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(217, 229, 51, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_15 = QtGui.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(221, 250, 51, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.slider_delay3Fine = QtGui.QSlider(self.centralwidget)
        self.slider_delay3Fine.setGeometry(QtCore.QRect(249, 20, 21, 160))
        self.slider_delay3Fine.setMaximum(127)
        self.slider_delay3Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay3Fine.setObjectName(_fromUtf8("slider_delay3Fine"))
        self.slider_pitchBase = QtGui.QSlider(self.centralwidget)
        self.slider_pitchBase.setGeometry(QtCore.QRect(379, 20, 50, 160))
        self.slider_pitchBase.setMaximum(3)
        self.slider_pitchBase.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchBase.setObjectName(_fromUtf8("slider_pitchBase"))
        self.label_delay3Fine = QtGui.QLabel(self.centralwidget)
        self.label_delay3Fine.setGeometry(QtCore.QRect(250, 180, 21, 17))
        self.label_delay3Fine.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay3Fine.setObjectName(_fromUtf8("label_delay3Fine"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(390, 198, 31, 17))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(430, 250, 31, 17))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(424, 198, 51, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(476, 197, 41, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(390, 230, 121, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_21 = QtGui.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(30, 580, 81, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_27 = QtGui.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(40, 470, 31, 31))
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(80, 470, 31, 31))
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.slider_decayTime = QtGui.QSlider(self.centralwidget)
        self.slider_decayTime.setGeometry(QtCore.QRect(549, 20, 50, 160))
        self.slider_decayTime.setMaximum(14)
        self.slider_decayTime.setOrientation(QtCore.Qt.Vertical)
        self.slider_decayTime.setObjectName(_fromUtf8("slider_decayTime"))
        self.slider_trebleDecay = QtGui.QSlider(self.centralwidget)
        self.slider_trebleDecay.setGeometry(QtCore.QRect(603, 20, 50, 160))
        self.slider_trebleDecay.setMaximum(15)
        self.slider_trebleDecay.setOrientation(QtCore.Qt.Vertical)
        self.slider_trebleDecay.setObjectName(_fromUtf8("slider_trebleDecay"))
        self.slider_bassMultiply = QtGui.QSlider(self.centralwidget)
        self.slider_bassMultiply.setGeometry(QtCore.QRect(653, 20, 50, 160))
        self.slider_bassMultiply.setMaximum(31)
        self.slider_bassMultiply.setOrientation(QtCore.Qt.Vertical)
        self.slider_bassMultiply.setObjectName(_fromUtf8("slider_bassMultiply"))
        self.slider_size = QtGui.QSlider(self.centralwidget)
        self.slider_size.setGeometry(QtCore.QRect(703, 20, 50, 160))
        self.slider_size.setMaximum(127)
        self.slider_size.setOrientation(QtCore.Qt.Vertical)
        self.slider_size.setObjectName(_fromUtf8("slider_size"))
        self.label_pitchBase = QtGui.QLabel(self.centralwidget)
        self.label_pitchBase.setGeometry(QtCore.QRect(390, 180, 21, 17))
        self.label_pitchBase.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchBase.setObjectName(_fromUtf8("label_pitchBase"))
        self.label_pitchInterval = QtGui.QLabel(self.centralwidget)
        self.label_pitchInterval.setGeometry(QtCore.QRect(430, 180, 21, 17))
        self.label_pitchInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchInterval.setObjectName(_fromUtf8("label_pitchInterval"))
        self.label_pitchAdjust = QtGui.QLabel(self.centralwidget)
        self.label_pitchAdjust.setGeometry(QtCore.QRect(480, 180, 21, 17))
        self.label_pitchAdjust.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchAdjust.setObjectName(_fromUtf8("label_pitchAdjust"))
        self.label_decayTime = QtGui.QLabel(self.centralwidget)
        self.label_decayTime.setGeometry(QtCore.QRect(560, 180, 21, 17))
        self.label_decayTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_decayTime.setObjectName(_fromUtf8("label_decayTime"))
        self.label_trebleDecay = QtGui.QLabel(self.centralwidget)
        self.label_trebleDecay.setGeometry(QtCore.QRect(613, 180, 21, 17))
        self.label_trebleDecay.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trebleDecay.setObjectName(_fromUtf8("label_trebleDecay"))
        self.label_bassMultiply = QtGui.QLabel(self.centralwidget)
        self.label_bassMultiply.setGeometry(QtCore.QRect(664, 180, 21, 17))
        self.label_bassMultiply.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bassMultiply.setObjectName(_fromUtf8("label_bassMultiply"))
        self.label_size = QtGui.QLabel(self.centralwidget)
        self.label_size.setGeometry(QtCore.QRect(716, 180, 21, 17))
        self.label_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_size.setObjectName(_fromUtf8("label_size"))
        self.label_diffusion = QtGui.QLabel(self.centralwidget)
        self.label_diffusion.setGeometry(QtCore.QRect(760, 180, 21, 17))
        self.label_diffusion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diffusion.setObjectName(_fromUtf8("label_diffusion"))
        self.slider_highCutFilter = QtGui.QSlider(self.centralwidget)
        self.slider_highCutFilter.setGeometry(QtCore.QRect(30, 290, 50, 160))
        self.slider_highCutFilter.setMaximum(15)
        self.slider_highCutFilter.setOrientation(QtCore.Qt.Vertical)
        self.slider_highCutFilter.setObjectName(_fromUtf8("slider_highCutFilter"))
        self.slider_lowCutFilter = QtGui.QSlider(self.centralwidget)
        self.slider_lowCutFilter.setGeometry(QtCore.QRect(70, 290, 50, 160))
        self.slider_lowCutFilter.setMaximum(31)
        self.slider_lowCutFilter.setOrientation(QtCore.Qt.Vertical)
        self.slider_lowCutFilter.setObjectName(_fromUtf8("slider_lowCutFilter"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(29, 9, 251, 261))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.slider_feedback1.raise_()
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 10, 151, 261))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.slider_pitchInterval = QtGui.QSlider(self.frame_2)
        self.slider_pitchInterval.setGeometry(QtCore.QRect(49, 10, 50, 160))
        self.slider_pitchInterval.setMaximum(36)
        self.slider_pitchInterval.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchInterval.setObjectName(_fromUtf8("slider_pitchInterval"))
        self.slider_pitchAdjust = QtGui.QSlider(self.frame_2)
        self.slider_pitchAdjust.setGeometry(QtCore.QRect(99, 10, 50, 160))
        self.slider_pitchAdjust.setMaximum(127)
        self.slider_pitchAdjust.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchAdjust.setObjectName(_fromUtf8("slider_pitchAdjust"))
        self.slider_pitchInterval.raise_()
        self.slider_pitchAdjust.raise_()
        self.slider_pitchAdjust.raise_()
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(536, 10, 341, 261))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_22 = QtGui.QLabel(self.frame_3)
        self.label_22.setGeometry(QtCore.QRect(20, 190, 41, 31))
        self.label_22.setWordWrap(True)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_25 = QtGui.QLabel(self.frame_3)
        self.label_25.setGeometry(QtCore.QRect(176, 189, 31, 17))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_23 = QtGui.QLabel(self.frame_3)
        self.label_23.setGeometry(QtCore.QRect(70, 175, 41, 61))
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.frame_3)
        self.label_24.setGeometry(QtCore.QRect(123, 188, 51, 31))
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.slider_reverbBalance = QtGui.QSlider(self.frame_3)
        self.slider_reverbBalance.setGeometry(QtCore.QRect(267, 10, 50, 160))
        self.slider_reverbBalance.setMaximum(127)
        self.slider_reverbBalance.setOrientation(QtCore.Qt.Vertical)
        self.slider_reverbBalance.setObjectName(_fromUtf8("slider_reverbBalance"))
        self.label_reverbBalance = QtGui.QLabel(self.frame_3)
        self.label_reverbBalance.setGeometry(QtCore.QRect(283, 170, 21, 17))
        self.label_reverbBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reverbBalance.setObjectName(_fromUtf8("label_reverbBalance"))
        self.label_reverbBalance_2 = QtGui.QLabel(self.frame_3)
        self.label_reverbBalance_2.setGeometry(QtCore.QRect(270, 180, 56, 31))
        self.label_reverbBalance_2.setWordWrap(True)
        self.label_reverbBalance_2.setObjectName(_fromUtf8("label_reverbBalance_2"))
        self.line_5 = QtGui.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(20, 220, 311, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_34 = QtGui.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(160, 240, 41, 17))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.slider_diffusion = QtGui.QSlider(self.frame_3)
        self.slider_diffusion.setGeometry(QtCore.QRect(217, 10, 50, 160))
        self.slider_diffusion.setMaximum(100)
        self.slider_diffusion.setOrientation(QtCore.Qt.Vertical)
        self.slider_diffusion.setObjectName(_fromUtf8("slider_diffusion"))
        self.label_26 = QtGui.QLabel(self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(207, 190, 56, 17))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_highCutFilter = QtGui.QLabel(self.centralwidget)
        self.label_highCutFilter.setGeometry(QtCore.QRect(40, 450, 21, 17))
        self.label_highCutFilter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_highCutFilter.setObjectName(_fromUtf8("label_highCutFilter"))
        self.label_lowCutFilter = QtGui.QLabel(self.centralwidget)
        self.label_lowCutFilter.setGeometry(QtCore.QRect(80, 450, 21, 17))
        self.label_lowCutFilter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lowCutFilter.setObjectName(_fromUtf8("label_lowCutFilter"))
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(30, 280, 301, 261))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_50 = QtGui.QLabel(self.frame_5)
        self.label_50.setGeometry(QtCore.QRect(80, 240, 151, 17))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.line_6 = QtGui.QFrame(self.frame_5)
        self.line_6.setGeometry(QtCore.QRect(10, 230, 281, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_LFORate = QtGui.QLabel(self.frame_5)
        self.label_LFORate.setGeometry(QtCore.QRect(153, 170, 21, 17))
        self.label_LFORate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LFORate.setObjectName(_fromUtf8("label_LFORate"))
        self.slider_outputBalance = QtGui.QSlider(self.frame_5)
        self.slider_outputBalance.setGeometry(QtCore.QRect(90, 10, 50, 160))
        self.slider_outputBalance.setMaximum(127)
        self.slider_outputBalance.setOrientation(QtCore.Qt.Vertical)
        self.slider_outputBalance.setObjectName(_fromUtf8("slider_outputBalance"))
        self.label_outputBalance = QtGui.QLabel(self.frame_5)
        self.label_outputBalance.setGeometry(QtCore.QRect(100, 170, 21, 17))
        self.label_outputBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputBalance.setObjectName(_fromUtf8("label_outputBalance"))
        self.label_30 = QtGui.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(100, 190, 56, 31))
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.slider_LFORate = QtGui.QSlider(self.frame_5)
        self.slider_LFORate.setGeometry(QtCore.QRect(143, 10, 50, 160))
        self.slider_LFORate.setMaximum(127)
        self.slider_LFORate.setOrientation(QtCore.Qt.Vertical)
        self.slider_LFORate.setObjectName(_fromUtf8("slider_LFORate"))
        self.label_33 = QtGui.QLabel(self.frame_5)
        self.label_33.setGeometry(QtCore.QRect(153, 190, 31, 31))
        self.label_33.setWordWrap(True)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.slider_outputLevel = QtGui.QSlider(self.frame_5)
        self.slider_outputLevel.setGeometry(QtCore.QRect(184, 11, 50, 160))
        self.slider_outputLevel.setMaximum(127)
        self.slider_outputLevel.setOrientation(QtCore.Qt.Vertical)
        self.slider_outputLevel.setObjectName(_fromUtf8("slider_outputLevel"))
        self.slider_inputLevel = QtGui.QSlider(self.frame_5)
        self.slider_inputLevel.setGeometry(QtCore.QRect(240, 10, 50, 160))
        self.slider_inputLevel.setMaximum(127)
        self.slider_inputLevel.setOrientation(QtCore.Qt.Vertical)
        self.slider_inputLevel.setObjectName(_fromUtf8("slider_inputLevel"))
        self.label_outputLevel = QtGui.QLabel(self.frame_5)
        self.label_outputLevel.setGeometry(QtCore.QRect(198, 172, 21, 17))
        self.label_outputLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputLevel.setObjectName(_fromUtf8("label_outputLevel"))
        self.label_inputLevel = QtGui.QLabel(self.frame_5)
        self.label_inputLevel.setGeometry(QtCore.QRect(250, 170, 21, 17))
        self.label_inputLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inputLevel.setObjectName(_fromUtf8("label_inputLevel"))
        self.label_31 = QtGui.QLabel(self.frame_5)
        self.label_31.setGeometry(QtCore.QRect(195, 190, 56, 31))
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.label_32 = QtGui.QLabel(self.frame_5)
        self.label_32.setGeometry(QtCore.QRect(249, 190, 41, 31))
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_50.raise_()
        self.line_6.raise_()
        self.slider_outputBalance.raise_()
        self.label_LFORate.raise_()
        self.slider_outputBalance.raise_()
        self.label_outputBalance.raise_()
        self.label_30.raise_()
        self.slider_LFORate.raise_()
        self.label_33.raise_()
        self.slider_outputLevel.raise_()
        self.slider_inputLevel.raise_()
        self.label_outputLevel.raise_()
        self.label_inputLevel.raise_()
        self.label_31.raise_()
        self.label_32.raise_()
        self.slider_highCutFilter.raise_()
        self.comboBox_midiPort = QtGui.QComboBox(self.centralwidget)
        self.comboBox_midiPort.setGeometry(QtCore.QRect(80, 550, 81, 27))
        self.comboBox_midiPort.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_midiPort.setObjectName(_fromUtf8("comboBox_midiPort"))
        self.logConsole = QtGui.QPlainTextEdit(self.centralwidget)
        self.logConsole.setGeometry(QtCore.QRect(340, 280, 531, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.logConsole.setFont(font)
        self.logConsole.setObjectName(_fromUtf8("logConsole"))
        self.btn_loop = QtGui.QPushButton(self.centralwidget)
        self.btn_loop.setGeometry(QtCore.QRect(290, 10, 51, 27))
        self.btn_loop.setCheckable(True)
        self.btn_loop.setObjectName(_fromUtf8("btn_loop"))
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame_5.raise_()
        self.frame.raise_()
        self.slider_delay1Coarse.raise_()
        self.slider_delay1Fine.raise_()
        self.slider_feedback1.raise_()
        self.slider_delay2Coarse.raise_()
        self.slider_delay2Fine.raise_()
        self.slider_feedback2.raise_()
        self.slider_delay3Coarse.raise_()
        self.label_delay1Coarse.raise_()
        self.label_delay1Fine.raise_()
        self.label_feedback1.raise_()
        self.label_delay2Coarse.raise_()
        self.label_delay2Fine.raise_()
        self.label_feedback2.raise_()
        self.label_delay3Coarse.raise_()
        self.spinbox_midiChannel.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.line.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.line_2.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.line_3.raise_()
        self.label_15.raise_()
        self.slider_delay3Fine.raise_()
        self.slider_pitchBase.raise_()
        self.label_delay3Fine.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.line_4.raise_()
        self.label_21.raise_()
        self.label_27.raise_()
        self.label_28.raise_()
        self.slider_decayTime.raise_()
        self.slider_trebleDecay.raise_()
        self.slider_bassMultiply.raise_()
        self.slider_size.raise_()
        self.label_pitchBase.raise_()
        self.label_pitchInterval.raise_()
        self.label_pitchAdjust.raise_()
        self.label_decayTime.raise_()
        self.label_trebleDecay.raise_()
        self.label_bassMultiply.raise_()
        self.label_size.raise_()
        self.label_diffusion.raise_()
        self.slider_highCutFilter.raise_()
        self.slider_lowCutFilter.raise_()
        self.label_highCutFilter.raise_()
        self.label_lowCutFilter.raise_()
        self.comboBox_midiPort.raise_()
        self.logConsole.raise_()
        self.btn_loop.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lexicon LXP-5 Editor", None))
        self.label_delay1Coarse.setText(_translate("MainWindow", "0", None))
        self.label_delay1Fine.setText(_translate("MainWindow", "0", None))
        self.label_feedback1.setText(_translate("MainWindow", "0", None))
        self.label_delay2Coarse.setText(_translate("MainWindow", "0", None))
        self.label_delay2Fine.setText(_translate("MainWindow", "0", None))
        self.label_feedback2.setText(_translate("MainWindow", "0", None))
        self.label_delay3Coarse.setText(_translate("MainWindow", "0", None))
        self.label_8.setText(_translate("MainWindow", "Time", None))
        self.label_9.setText(_translate("MainWindow", "Delay 1", None))
        self.label_10.setText(_translate("MainWindow", "Fb", None))
        self.label_11.setText(_translate("MainWindow", "Time", None))
        self.label_12.setText(_translate("MainWindow", "Delay 2", None))
        self.label_13.setText(_translate("MainWindow", "Fb", None))
        self.label_14.setText(_translate("MainWindow", "Time", None))
        self.label_15.setText(_translate("MainWindow", "Delay 3", None))
        self.label_delay3Fine.setText(_translate("MainWindow", "0", None))
        self.label_17.setText(_translate("MainWindow", "Base", None))
        self.label_18.setText(_translate("MainWindow", "Pitch", None))
        self.label_19.setText(_translate("MainWindow", "Interval", None))
        self.label_20.setText(_translate("MainWindow", "Adjust", None))
        self.label_21.setText(_translate("MainWindow", "MIDI Channel", None))
        self.label_27.setText(_translate("MainWindow", "High Cut", None))
        self.label_28.setText(_translate("MainWindow", "Low Cut", None))
        self.label_pitchBase.setText(_translate("MainWindow", "0", None))
        self.label_pitchInterval.setText(_translate("MainWindow", "0", None))
        self.label_pitchAdjust.setText(_translate("MainWindow", "0", None))
        self.label_decayTime.setText(_translate("MainWindow", "0", None))
        self.label_trebleDecay.setText(_translate("MainWindow", "0", None))
        self.label_bassMultiply.setText(_translate("MainWindow", "0", None))
        self.label_size.setText(_translate("MainWindow", "0", None))
        self.label_diffusion.setText(_translate("MainWindow", "0", None))
        self.label_22.setText(_translate("MainWindow", "Decay Time", None))
        self.label_25.setText(_translate("MainWindow", "Size", None))
        self.label_23.setText(_translate("MainWindow", "Treble Decay", None))
        self.label_24.setText(_translate("MainWindow", "Bass Multiply", None))
        self.label_reverbBalance.setText(_translate("MainWindow", "0", None))
        self.label_reverbBalance_2.setText(_translate("MainWindow", "Balance", None))
        self.label_34.setText(_translate("MainWindow", "Reverb", None))
        self.label_26.setText(_translate("MainWindow", "Diffusion", None))
        self.label_highCutFilter.setText(_translate("MainWindow", "0", None))
        self.label_lowCutFilter.setText(_translate("MainWindow", "0", None))
        self.label_50.setText(_translate("MainWindow", "Equalization and Balance", None))
        self.label_LFORate.setText(_translate("MainWindow", "0", None))
        self.label_outputBalance.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "Output Balance", None))
        self.label_33.setText(_translate("MainWindow", "LFO Rate", None))
        self.label_outputLevel.setText(_translate("MainWindow", "0", None))
        self.label_inputLevel.setText(_translate("MainWindow", "0", None))
        self.label_31.setText(_translate("MainWindow", "Output Level", None))
        self.label_32.setText(_translate("MainWindow", "Input Level", None))
        self.btn_loop.setText(_translate("MainWindow", "Loop", None))

