# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(875, 622)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 361, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(260, 230, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.btn_loop = QtWidgets.QPushButton(self.frame)
        self.btn_loop.setGeometry(QtCore.QRect(10, 250, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_loop.setFont(font)
        self.btn_loop.setCheckable(True)
        self.btn_loop.setObjectName("btn_loop")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 258, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 10, 71, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_delay2Time = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_delay2Time.setFont(font)
        self.label_delay2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay2Time.setObjectName("label_delay2Time")
        self.verticalLayout_2.addWidget(self.label_delay2Time)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slider_delay2Coarse = QtWidgets.QSlider(self.layoutWidget)
        self.slider_delay2Coarse.setMaximum(126)
        self.slider_delay2Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay2Coarse.setObjectName("slider_delay2Coarse")
        self.horizontalLayout_2.addWidget(self.slider_delay2Coarse)
        self.slider_delay2Fine = QtWidgets.QSlider(self.layoutWidget)
        self.slider_delay2Fine.setMaximum(127)
        self.slider_delay2Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay2Fine.setObjectName("slider_delay2Fine")
        self.horizontalLayout_2.addWidget(self.slider_delay2Fine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_delay1Time = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_delay1Time.setFont(font)
        self.label_delay1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay1Time.setObjectName("label_delay1Time")
        self.verticalLayout.addWidget(self.label_delay1Time)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.slider_delay1Coarse = QtWidgets.QSlider(self.layoutWidget1)
        self.slider_delay1Coarse.setMaximum(127)
        self.slider_delay1Coarse.setPageStep(10)
        self.slider_delay1Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay1Coarse.setObjectName("slider_delay1Coarse")
        self.horizontalLayout.addWidget(self.slider_delay1Coarse)
        self.slider_delay1Fine = QtWidgets.QSlider(self.layoutWidget1)
        self.slider_delay1Fine.setMaximum(127)
        self.slider_delay1Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay1Fine.setObjectName("slider_delay1Fine")
        self.horizontalLayout.addWidget(self.slider_delay1Fine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(240, 10, 71, 241))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_feedback1 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_feedback1.setFont(font)
        self.label_feedback1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback1.setObjectName("label_feedback1")
        self.verticalLayout_4.addWidget(self.label_feedback1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.slider_feedback1 = QtWidgets.QSlider(self.layoutWidget2)
        self.slider_feedback1.setMaximum(127)
        self.slider_feedback1.setOrientation(QtCore.Qt.Vertical)
        self.slider_feedback1.setObjectName("slider_feedback1")
        self.horizontalLayout_5.addWidget(self.slider_feedback1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(285, 10, 71, 241))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_feedback2 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_feedback2.setFont(font)
        self.label_feedback2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback2.setObjectName("label_feedback2")
        self.verticalLayout_5.addWidget(self.label_feedback2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.slider_feedback2 = QtWidgets.QSlider(self.layoutWidget3)
        self.slider_feedback2.setMaximum(126)
        self.slider_feedback2.setOrientation(QtCore.Qt.Vertical)
        self.slider_feedback2.setObjectName("slider_feedback2")
        self.horizontalLayout_6.addWidget(self.slider_feedback2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_5.addWidget(self.label_12)
        self.layoutWidget4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(170, 10, 71, 241))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_delay3Time = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_delay3Time.setFont(font)
        self.label_delay3Time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay3Time.setObjectName("label_delay3Time")
        self.verticalLayout_3.addWidget(self.label_delay3Time)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slider_delay3Coarse = QtWidgets.QSlider(self.layoutWidget4)
        self.slider_delay3Coarse.setMaximum(126)
        self.slider_delay3Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay3Coarse.setObjectName("slider_delay3Coarse")
        self.horizontalLayout_3.addWidget(self.slider_delay3Coarse)
        self.slider_delay3Fine = QtWidgets.QSlider(self.layoutWidget4)
        self.slider_delay3Fine.setMaximum(127)
        self.slider_delay3Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay3Fine.setObjectName("slider_delay3Fine")
        self.horizontalLayout_3.addWidget(self.slider_delay3Fine, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.layoutWidget.raise_()
        self.btn_loop.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_15.raise_()
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(410, 10, 171, 281))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(70, 258, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.layoutWidget5 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 10, 71, 241))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_pitchBase = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_pitchBase.setFont(font)
        self.label_pitchBase.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchBase.setWordWrap(False)
        self.label_pitchBase.setObjectName("label_pitchBase")
        self.verticalLayout_21.addWidget(self.label_pitchBase)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slider_pitchBase = QtWidgets.QSlider(self.layoutWidget5)
        self.slider_pitchBase.setMaximum(3)
        self.slider_pitchBase.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchBase.setObjectName("slider_pitchBase")
        self.horizontalLayout_4.addWidget(self.slider_pitchBase)
        self.verticalLayout_21.addLayout(self.horizontalLayout_4)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_21.addWidget(self.label_29)
        self.layoutWidget6 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(100, 10, 71, 241))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_pitchAdjust = QtWidgets.QLabel(self.layoutWidget6)
        self.label_pitchAdjust.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchAdjust.setObjectName("label_pitchAdjust")
        self.verticalLayout_20.addWidget(self.label_pitchAdjust)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.slider_pitchAdjust = QtWidgets.QSlider(self.layoutWidget6)
        self.slider_pitchAdjust.setEnabled(True)
        self.slider_pitchAdjust.setMaximum(127)
        self.slider_pitchAdjust.setProperty("value", 64)
        self.slider_pitchAdjust.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchAdjust.setObjectName("slider_pitchAdjust")
        self.horizontalLayout_8.addWidget(self.slider_pitchAdjust)
        self.verticalLayout_20.addLayout(self.horizontalLayout_8)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_20.addWidget(self.label_20)
        self.layoutWidget7 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(50, 10, 71, 241))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_pitchInterval = QtWidgets.QLabel(self.layoutWidget7)
        self.label_pitchInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchInterval.setObjectName("label_pitchInterval")
        self.verticalLayout_19.addWidget(self.label_pitchInterval)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.slider_pitchInterval = QtWidgets.QSlider(self.layoutWidget7)
        self.slider_pitchInterval.setMaximum(36)
        self.slider_pitchInterval.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchInterval.setObjectName("slider_pitchInterval")
        self.horizontalLayout_7.addWidget(self.slider_pitchInterval)
        self.verticalLayout_19.addLayout(self.horizontalLayout_7)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_19.addWidget(self.label_19)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_18.raise_()
        self.layoutWidget.raise_()
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(590, 10, 271, 281))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(115, 258, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.layoutWidget8 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(50, 10, 71, 241))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_trebleDecay = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_trebleDecay.setFont(font)
        self.label_trebleDecay.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trebleDecay.setObjectName("label_trebleDecay")
        self.verticalLayout_10.addWidget(self.label_trebleDecay)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.slider_trebleDecay = QtWidgets.QSlider(self.layoutWidget8)
        self.slider_trebleDecay.setMaximum(15)
        self.slider_trebleDecay.setProperty("value", 15)
        self.slider_trebleDecay.setSliderPosition(15)
        self.slider_trebleDecay.setOrientation(QtCore.Qt.Vertical)
        self.slider_trebleDecay.setObjectName("slider_trebleDecay")
        self.horizontalLayout_12.addWidget(self.slider_trebleDecay, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_10.addWidget(self.label_35)
        self.layoutWidget9 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(150, 10, 71, 241))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_size = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_size.setFont(font)
        self.label_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_size.setObjectName("label_size")
        self.verticalLayout_12.addWidget(self.label_size)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.slider_size = QtWidgets.QSlider(self.layoutWidget9)
        self.slider_size.setMaximum(25)
        self.slider_size.setOrientation(QtCore.Qt.Vertical)
        self.slider_size.setObjectName("slider_size")
        self.horizontalLayout_14.addWidget(self.slider_size, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_12.addWidget(self.label_23)
        self.layoutWidget10 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(200, 10, 71, 241))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_diffusion = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_diffusion.setFont(font)
        self.label_diffusion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diffusion.setObjectName("label_diffusion")
        self.verticalLayout_13.addWidget(self.label_diffusion)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.slider_diffusion = QtWidgets.QSlider(self.layoutWidget10)
        self.slider_diffusion.setMaximum(100)
        self.slider_diffusion.setOrientation(QtCore.Qt.Vertical)
        self.slider_diffusion.setObjectName("slider_diffusion")
        self.horizontalLayout_15.addWidget(self.slider_diffusion, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_13.addWidget(self.label_26)
        self.layoutWidget11 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget11.setGeometry(QtCore.QRect(0, 10, 71, 241))
        self.layoutWidget11.setObjectName("layoutWidget11")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_decayTime = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_decayTime.setFont(font)
        self.label_decayTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_decayTime.setObjectName("label_decayTime")
        self.verticalLayout_9.addWidget(self.label_decayTime)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.slider_decayTime = QtWidgets.QSlider(self.layoutWidget11)
        self.slider_decayTime.setMaximum(14)
        self.slider_decayTime.setOrientation(QtCore.Qt.Vertical)
        self.slider_decayTime.setObjectName("slider_decayTime")
        self.horizontalLayout_11.addWidget(self.slider_decayTime, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.layoutWidget12 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget12.setGeometry(QtCore.QRect(100, 10, 71, 241))
        self.layoutWidget12.setObjectName("layoutWidget12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_bassMultiply = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_bassMultiply.setFont(font)
        self.label_bassMultiply.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bassMultiply.setObjectName("label_bassMultiply")
        self.verticalLayout_11.addWidget(self.label_bassMultiply)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.slider_bassMultiply = QtWidgets.QSlider(self.layoutWidget12)
        self.slider_bassMultiply.setMaximum(31)
        self.slider_bassMultiply.setOrientation(QtCore.Qt.Vertical)
        self.slider_bassMultiply.setObjectName("slider_bassMultiply")
        self.horizontalLayout_13.addWidget(self.slider_bassMultiply)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_11.addWidget(self.label_38)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(590, 300, 271, 281))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_50 = QtWidgets.QLabel(self.frame_5)
        self.label_50.setGeometry(QtCore.QRect(110, 257, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.layoutWidget13 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.layoutWidget13.setObjectName("layoutWidget13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_reverbBalance = QtWidgets.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_reverbBalance.setFont(font)
        self.label_reverbBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reverbBalance.setObjectName("label_reverbBalance")
        self.verticalLayout_8.addWidget(self.label_reverbBalance)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.slider_reverbBalance = QtWidgets.QSlider(self.layoutWidget13)
        self.slider_reverbBalance.setMaximum(127)
        self.slider_reverbBalance.setProperty("value", 63)
        self.slider_reverbBalance.setOrientation(QtCore.Qt.Vertical)
        self.slider_reverbBalance.setObjectName("slider_reverbBalance")
        self.horizontalLayout_18.addWidget(self.slider_reverbBalance)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.label_reverbBalance_2 = QtWidgets.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_reverbBalance_2.setFont(font)
        self.label_reverbBalance_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reverbBalance_2.setWordWrap(True)
        self.label_reverbBalance_2.setObjectName("label_reverbBalance_2")
        self.verticalLayout_8.addWidget(self.label_reverbBalance_2)
        self.layoutWidget14 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget14.setGeometry(QtCore.QRect(60, 10, 71, 241))
        self.layoutWidget14.setObjectName("layoutWidget14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_outputBalance = QtWidgets.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_outputBalance.setFont(font)
        self.label_outputBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputBalance.setObjectName("label_outputBalance")
        self.verticalLayout_14.addWidget(self.label_outputBalance)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.slider_outputBalance = QtWidgets.QSlider(self.layoutWidget14)
        self.slider_outputBalance.setMaximum(127)
        self.slider_outputBalance.setProperty("value", 63)
        self.slider_outputBalance.setOrientation(QtCore.Qt.Vertical)
        self.slider_outputBalance.setObjectName("slider_outputBalance")
        self.horizontalLayout_19.addWidget(self.slider_outputBalance)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_14.addWidget(self.label_30)
        self.layoutWidget15 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget15.setGeometry(QtCore.QRect(110, 10, 71, 241))
        self.layoutWidget15.setObjectName("layoutWidget15")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.layoutWidget15)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_outputLevel = QtWidgets.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_outputLevel.setFont(font)
        self.label_outputLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputLevel.setObjectName("label_outputLevel")
        self.verticalLayout_22.addWidget(self.label_outputLevel)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.slider_outputLevel = QtWidgets.QSlider(self.layoutWidget15)
        self.slider_outputLevel.setMaximum(127)
        self.slider_outputLevel.setProperty("value", 127)
        self.slider_outputLevel.setOrientation(QtCore.Qt.Vertical)
        self.slider_outputLevel.setObjectName("slider_outputLevel")
        self.horizontalLayout_21.addWidget(self.slider_outputLevel)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_22.addWidget(self.label_31)
        self.layoutWidget16 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget16.setGeometry(QtCore.QRect(160, 10, 81, 241))
        self.layoutWidget16.setObjectName("layoutWidget16")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget16)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_inputLevel = QtWidgets.QLabel(self.layoutWidget16)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_inputLevel.setFont(font)
        self.label_inputLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inputLevel.setObjectName("label_inputLevel")
        self.verticalLayout_23.addWidget(self.label_inputLevel)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.slider_inputLevel = QtWidgets.QSlider(self.layoutWidget16)
        self.slider_inputLevel.setMaximum(127)
        self.slider_inputLevel.setProperty("value", 127)
        self.slider_inputLevel.setOrientation(QtCore.Qt.Vertical)
        self.slider_inputLevel.setObjectName("slider_inputLevel")
        self.horizontalLayout_22.addWidget(self.slider_inputLevel)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget16)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_23.addWidget(self.label_32)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(440, 300, 141, 281))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget17 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget17.setGeometry(QtCore.QRect(60, 10, 71, 241))
        self.layoutWidget17.setObjectName("layoutWidget17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget17)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_lowCutFilter = QtWidgets.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_lowCutFilter.setFont(font)
        self.label_lowCutFilter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lowCutFilter.setObjectName("label_lowCutFilter")
        self.verticalLayout_7.addWidget(self.label_lowCutFilter)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.slider_lowCutFilter = QtWidgets.QSlider(self.layoutWidget17)
        self.slider_lowCutFilter.setMaximum(31)
        self.slider_lowCutFilter.setOrientation(QtCore.Qt.Vertical)
        self.slider_lowCutFilter.setObjectName("slider_lowCutFilter")
        self.horizontalLayout_17.addWidget(self.slider_lowCutFilter)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.layoutWidget18 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget18.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.layoutWidget18.setObjectName("layoutWidget18")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget18)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_highCutFilter = QtWidgets.QLabel(self.layoutWidget18)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_highCutFilter.setFont(font)
        self.label_highCutFilter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_highCutFilter.setObjectName("label_highCutFilter")
        self.verticalLayout_6.addWidget(self.label_highCutFilter)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.slider_highCutFilter = QtWidgets.QSlider(self.layoutWidget18)
        self.slider_highCutFilter.setMaximum(15)
        self.slider_highCutFilter.setProperty("value", 15)
        self.slider_highCutFilter.setOrientation(QtCore.Qt.Vertical)
        self.slider_highCutFilter.setObjectName("slider_highCutFilter")
        self.horizontalLayout_16.addWidget(self.slider_highCutFilter)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget18)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_6.addWidget(self.label_27)
        self.label_51 = QtWidgets.QLabel(self.frame_4)
        self.label_51.setGeometry(QtCore.QRect(40, 257, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.layoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 463, 301, 51))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.slider_LFORate = QtWidgets.QSlider(self.layoutWidget_7)
        self.slider_LFORate.setMaximum(127)
        self.slider_LFORate.setOrientation(QtCore.Qt.Horizontal)
        self.slider_LFORate.setObjectName("slider_LFORate")
        self.verticalLayout_29.addWidget(self.slider_LFORate)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_29.addWidget(self.label_36, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_28.addLayout(self.verticalLayout_29)
        self.layoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 523, 201, 71))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.spinbox_midiChannel = QtWidgets.QSpinBox(self.layoutWidget_8)
        self.spinbox_midiChannel.setMinimum(1)
        self.spinbox_midiChannel.setMaximum(16)
        self.spinbox_midiChannel.setObjectName("spinbox_midiChannel")
        self.horizontalLayout_32.addWidget(self.spinbox_midiChannel, 0, QtCore.Qt.AlignLeft)
        self.comboBox_midiPort = QtWidgets.QComboBox(self.layoutWidget_8)
        self.comboBox_midiPort.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboBox_midiPort.setObjectName("comboBox_midiPort")
        self.horizontalLayout_32.addWidget(self.comboBox_midiPort)
        self.verticalLayout_33.addLayout(self.horizontalLayout_32)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_33.addWidget(self.label_39)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(280, 463, 91, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_LFORateHz = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_LFORateHz.setFont(font)
        self.label_LFORateHz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_LFORateHz.setObjectName("label_LFORateHz")
        self.verticalLayout_15.addWidget(self.label_LFORateHz)
        self.label_LFORateBPM = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_LFORateBPM.setFont(font)
        self.label_LFORateBPM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_LFORateBPM.setObjectName("label_LFORateBPM")
        self.verticalLayout_15.addWidget(self.label_LFORateBPM)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(0, 300, 431, 131))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.dial_patch2Threshold = QtWidgets.QDial(self.widget1)
        self.dial_patch2Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch2Threshold.setFont(font)
        self.dial_patch2Threshold.setMaximum(127)
        self.dial_patch2Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch2Threshold.setObjectName("dial_patch2Threshold")
        self.horizontalLayout_10.addWidget(self.dial_patch2Threshold)
        self.dial_patch2ScaleFactor = QtWidgets.QDial(self.widget1)
        self.dial_patch2ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch2ScaleFactor.setFont(font)
        self.dial_patch2ScaleFactor.setMinimum(-64)
        self.dial_patch2ScaleFactor.setMaximum(63)
        self.dial_patch2ScaleFactor.setProperty("value", 0)
        self.dial_patch2ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch2ScaleFactor.setObjectName("dial_patch2ScaleFactor")
        self.horizontalLayout_10.addWidget(self.dial_patch2ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 6, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.dial_patch4Threshold = QtWidgets.QDial(self.widget1)
        self.dial_patch4Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch4Threshold.setFont(font)
        self.dial_patch4Threshold.setMaximum(127)
        self.dial_patch4Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch4Threshold.setObjectName("dial_patch4Threshold")
        self.horizontalLayout_23.addWidget(self.dial_patch4Threshold)
        self.dial_patch4ScaleFactor = QtWidgets.QDial(self.widget1)
        self.dial_patch4ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch4ScaleFactor.setFont(font)
        self.dial_patch4ScaleFactor.setMinimum(-64)
        self.dial_patch4ScaleFactor.setMaximum(63)
        self.dial_patch4ScaleFactor.setProperty("value", 0)
        self.dial_patch4ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch4ScaleFactor.setObjectName("dial_patch4ScaleFactor")
        self.horizontalLayout_23.addWidget(self.dial_patch4ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_23, 3, 10, 1, 1)
        self.comboBox_patch4Destination = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch4Destination.setFont(font)
        self.comboBox_patch4Destination.setObjectName("comboBox_patch4Destination")
        self.gridLayout.addWidget(self.comboBox_patch4Destination, 2, 10, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox_patch2Destination = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch2Destination.setFont(font)
        self.comboBox_patch2Destination.setObjectName("comboBox_patch2Destination")
        self.gridLayout.addWidget(self.comboBox_patch2Destination, 2, 6, 1, 1)
        self.comboBox_patch3Destination = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch3Destination.setFont(font)
        self.comboBox_patch3Destination.setObjectName("comboBox_patch3Destination")
        self.gridLayout.addWidget(self.comboBox_patch3Destination, 2, 8, 1, 1)
        self.comboBox_patch1Destination = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch1Destination.setFont(font)
        self.comboBox_patch1Destination.setObjectName("comboBox_patch1Destination")
        self.gridLayout.addWidget(self.comboBox_patch1Destination, 2, 3, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.dial_patch3Threshold = QtWidgets.QDial(self.widget1)
        self.dial_patch3Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch3Threshold.setFont(font)
        self.dial_patch3Threshold.setMaximum(127)
        self.dial_patch3Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch3Threshold.setObjectName("dial_patch3Threshold")
        self.horizontalLayout_20.addWidget(self.dial_patch3Threshold)
        self.dial_patch3ScaleFactor = QtWidgets.QDial(self.widget1)
        self.dial_patch3ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch3ScaleFactor.setFont(font)
        self.dial_patch3ScaleFactor.setMinimum(-64)
        self.dial_patch3ScaleFactor.setMaximum(63)
        self.dial_patch3ScaleFactor.setProperty("value", 0)
        self.dial_patch3ScaleFactor.setOrientation(QtCore.Qt.Vertical)
        self.dial_patch3ScaleFactor.setObjectName("dial_patch3ScaleFactor")
        self.horizontalLayout_20.addWidget(self.dial_patch3ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_20, 3, 8, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.dial_patch1Threshold = QtWidgets.QDial(self.widget1)
        self.dial_patch1Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch1Threshold.setFont(font)
        self.dial_patch1Threshold.setMaximum(127)
        self.dial_patch1Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch1Threshold.setObjectName("dial_patch1Threshold")
        self.horizontalLayout_9.addWidget(self.dial_patch1Threshold)
        self.dial_patch1ScaleFactor = QtWidgets.QDial(self.widget1)
        self.dial_patch1ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch1ScaleFactor.setFont(font)
        self.dial_patch1ScaleFactor.setMinimum(-64)
        self.dial_patch1ScaleFactor.setMaximum(63)
        self.dial_patch1ScaleFactor.setProperty("value", 0)
        self.dial_patch1ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch1ScaleFactor.setObjectName("dial_patch1ScaleFactor")
        self.horizontalLayout_9.addWidget(self.dial_patch1ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.comboBox_patch2Source = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch2Source.setFont(font)
        self.comboBox_patch2Source.setObjectName("comboBox_patch2Source")
        self.gridLayout.addWidget(self.comboBox_patch2Source, 1, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 10, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_patch1Source = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch1Source.setFont(font)
        self.comboBox_patch1Source.setObjectName("comboBox_patch1Source")
        self.gridLayout.addWidget(self.comboBox_patch1Source, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_patch3Source = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch3Source.setFont(font)
        self.comboBox_patch3Source.setObjectName("comboBox_patch3Source")
        self.gridLayout.addWidget(self.comboBox_patch3Source, 1, 8, 1, 1)
        self.comboBox_patch4Source = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch4Source.setFont(font)
        self.comboBox_patch4Source.setObjectName("comboBox_patch4Source")
        self.gridLayout.addWidget(self.comboBox_patch4Source, 1, 10, 1, 1)
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame_5.raise_()
        self.frame.raise_()
        self.frame_4.raise_()
        self.layoutWidget_7.raise_()
        self.layoutWidget_8.raise_()
        self.label_LFORateBPM.raise_()
        self.label_LFORateHz.raise_()
        self.comboBox_patch1Source.raise_()
        self.comboBox_patch2Source.raise_()
        self.comboBox_patch3Source.raise_()
        self.comboBox_patch4Source.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.dial_patch1ScaleFactor.raise_()
        self.dial_patch1Threshold.raise_()
        self.dial_patch2ScaleFactor.raise_()
        self.dial_patch2Threshold.raise_()
        self.dial_patch3Threshold.raise_()
        self.dial_patch3ScaleFactor.raise_()
        self.dial_patch4Threshold.raise_()
        self.dial_patch4ScaleFactor.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lexicon LXP-5 Editor"))
        self.label_15.setText(_translate("MainWindow", "Feedback"))
        self.btn_loop.setText(_translate("MainWindow", "Loop"))
        self.label.setText(_translate("MainWindow", "Delay"))
        self.label_delay2Time.setText(_translate("MainWindow", "0.0 ms"))
        self.label_11.setText(_translate("MainWindow", "Delay 2<br>Time"))
        self.label_delay1Time.setText(_translate("MainWindow", "0.0 ms"))
        self.label_8.setText(_translate("MainWindow", "Delay 1<br>Time"))
        self.label_feedback1.setText(_translate("MainWindow", "0.0%"))
        self.label_10.setText(_translate("MainWindow", "Amt 1<br>"))
        self.label_feedback2.setText(_translate("MainWindow", "0.0%"))
        self.label_12.setText(_translate("MainWindow", "Amt 2<br>"))
        self.label_delay3Time.setText(_translate("MainWindow", "0.0 ms"))
        self.label_14.setText(_translate("MainWindow", "Delay 3<br>Time"))
        self.label_18.setText(_translate("MainWindow", "Pitch"))
        self.label_pitchBase.setText(_translate("MainWindow", "Defeat"))
        self.label_29.setText(_translate("MainWindow", "Base<br>"))
        self.label_pitchAdjust.setText(_translate("MainWindow", "+0"))
        self.label_20.setText(_translate("MainWindow", "Adjust<br>"))
        self.label_pitchInterval.setText(_translate("MainWindow", "+0 st"))
        self.label_19.setText(_translate("MainWindow", "Interval<br>"))
        self.label_34.setText(_translate("MainWindow", "Reverb"))
        self.label_trebleDecay.setText(_translate("MainWindow", "Full"))
        self.label_35.setText(_translate("MainWindow", "Treble<br>Decay"))
        self.label_size.setText(_translate("MainWindow", "8.0 m"))
        self.label_23.setText(_translate("MainWindow", "Size<br>"))
        self.label_diffusion.setText(_translate("MainWindow", "0.0%"))
        self.label_26.setText(_translate("MainWindow", "Diffusion<br>"))
        self.label_decayTime.setText(_translate("MainWindow", "0.5 sec"))
        self.label_37.setText(_translate("MainWindow", "Decay<br>"))
        self.label_bassMultiply.setText(_translate("MainWindow", "x0.30"))
        self.label_38.setText(_translate("MainWindow", "Bass<br>Multiply"))
        self.label_50.setText(_translate("MainWindow", "Levels"))
        self.label_reverbBalance.setText(_translate("MainWindow", "0"))
        self.label_reverbBalance_2.setText(_translate("MainWindow", "Reverb<br>Balance"))
        self.label_outputBalance.setText(_translate("MainWindow", "0"))
        self.label_30.setText(_translate("MainWindow", "Output<br>Balance"))
        self.label_outputLevel.setText(_translate("MainWindow", "100%"))
        self.label_31.setText(_translate("MainWindow", "Output<br>Level"))
        self.label_inputLevel.setText(_translate("MainWindow", "100%"))
        self.label_32.setText(_translate("MainWindow", "Input<br>Level"))
        self.label_lowCutFilter.setText(_translate("MainWindow", "Full"))
        self.label_28.setText(_translate("MainWindow", "Low<br>Cut"))
        self.label_highCutFilter.setText(_translate("MainWindow", "Full"))
        self.label_27.setText(_translate("MainWindow", "High<br>Cut"))
        self.label_51.setText(_translate("MainWindow", "Equalization"))
        self.label_36.setText(_translate("MainWindow", "LFO Rate"))
        self.label_39.setText(_translate("MainWindow", "MIDI Channel"))
        self.label_LFORateHz.setText(_translate("MainWindow", "0.066 Hz"))
        self.label_LFORateBPM.setText(_translate("MainWindow", "3.96 bpm"))
        self.dial_patch2Threshold.setToolTip(_translate("MainWindow", "Patch 2 Threshold"))
        self.dial_patch2ScaleFactor.setToolTip(_translate("MainWindow", "Patch 2 Scale Factor"))
        self.dial_patch4Threshold.setToolTip(_translate("MainWindow", "Patch 4 Threshold"))
        self.dial_patch4ScaleFactor.setToolTip(_translate("MainWindow", "Patch 4 Scale Factor"))
        self.label_9.setText(_translate("MainWindow", "Destination"))
        self.dial_patch3Threshold.setToolTip(_translate("MainWindow", "Patch 3 Threshold"))
        self.dial_patch3ScaleFactor.setToolTip(_translate("MainWindow", "Patch 3 Scale Factor"))
        self.dial_patch1Threshold.setToolTip(_translate("MainWindow", "Patch 1 Threshold"))
        self.dial_patch1ScaleFactor.setToolTip(_translate("MainWindow", "Patch 1 Scale Factor"))
        self.label_7.setText(_translate("MainWindow", "Threshold/<br>Scale Factor"))
        self.label_4.setText(_translate("MainWindow", "Patch 3"))
        self.label_2.setText(_translate("MainWindow", "Patch 1"))
        self.label_5.setText(_translate("MainWindow", "Patch 4"))
        self.label_3.setText(_translate("MainWindow", "Patch 2"))
        self.label_6.setText(_translate("MainWindow", "Source"))

