# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(875, 622)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 361, 281))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(260, 230, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.btn_loop = QtGui.QPushButton(self.frame)
        self.btn_loop.setGeometry(QtCore.QRect(10, 250, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_loop.setFont(font)
        self.btn_loop.setCheckable(True)
        self.btn_loop.setObjectName(_fromUtf8("btn_loop"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 258, 41, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(90, 10, 71, 241))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_delay2Time = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_delay2Time.setFont(font)
        self.label_delay2Time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay2Time.setObjectName(_fromUtf8("label_delay2Time"))
        self.verticalLayout_2.addWidget(self.label_delay2Time)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.slider_delay2Coarse = QtGui.QSlider(self.layoutWidget)
        self.slider_delay2Coarse.setMaximum(126)
        self.slider_delay2Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay2Coarse.setObjectName(_fromUtf8("slider_delay2Coarse"))
        self.horizontalLayout_2.addWidget(self.slider_delay2Coarse)
        self.slider_delay2Fine = QtGui.QSlider(self.layoutWidget)
        self.slider_delay2Fine.setMaximum(127)
        self.slider_delay2Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay2Fine.setObjectName(_fromUtf8("slider_delay2Fine"))
        self.horizontalLayout_2.addWidget(self.slider_delay2Fine)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_2.addWidget(self.label_11)
        self.layoutWidget1 = QtGui.QWidget(self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_delay1Time = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_delay1Time.setFont(font)
        self.label_delay1Time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay1Time.setObjectName(_fromUtf8("label_delay1Time"))
        self.verticalLayout.addWidget(self.label_delay1Time)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.slider_delay1Coarse = QtGui.QSlider(self.layoutWidget1)
        self.slider_delay1Coarse.setMaximum(127)
        self.slider_delay1Coarse.setPageStep(10)
        self.slider_delay1Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay1Coarse.setObjectName(_fromUtf8("slider_delay1Coarse"))
        self.horizontalLayout.addWidget(self.slider_delay1Coarse)
        self.slider_delay1Fine = QtGui.QSlider(self.layoutWidget1)
        self.slider_delay1Fine.setMaximum(127)
        self.slider_delay1Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay1Fine.setObjectName(_fromUtf8("slider_delay1Fine"))
        self.horizontalLayout.addWidget(self.slider_delay1Fine)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_8 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.layoutWidget2 = QtGui.QWidget(self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(240, 10, 71, 241))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_feedback1 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_feedback1.setFont(font)
        self.label_feedback1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback1.setObjectName(_fromUtf8("label_feedback1"))
        self.verticalLayout_4.addWidget(self.label_feedback1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.slider_feedback1 = QtGui.QSlider(self.layoutWidget2)
        self.slider_feedback1.setMaximum(127)
        self.slider_feedback1.setOrientation(QtCore.Qt.Vertical)
        self.slider_feedback1.setObjectName(_fromUtf8("slider_feedback1"))
        self.horizontalLayout_5.addWidget(self.slider_feedback1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.layoutWidget3 = QtGui.QWidget(self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(285, 10, 71, 241))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_feedback2 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_feedback2.setFont(font)
        self.label_feedback2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_feedback2.setObjectName(_fromUtf8("label_feedback2"))
        self.verticalLayout_5.addWidget(self.label_feedback2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.slider_feedback2 = QtGui.QSlider(self.layoutWidget3)
        self.slider_feedback2.setMaximum(126)
        self.slider_feedback2.setOrientation(QtCore.Qt.Vertical)
        self.slider_feedback2.setObjectName(_fromUtf8("slider_feedback2"))
        self.horizontalLayout_6.addWidget(self.slider_feedback2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.label_12 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.layoutWidget4 = QtGui.QWidget(self.frame)
        self.layoutWidget4.setGeometry(QtCore.QRect(170, 10, 71, 241))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_delay3Time = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_delay3Time.setFont(font)
        self.label_delay3Time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_delay3Time.setObjectName(_fromUtf8("label_delay3Time"))
        self.verticalLayout_3.addWidget(self.label_delay3Time)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.slider_delay3Coarse = QtGui.QSlider(self.layoutWidget4)
        self.slider_delay3Coarse.setMaximum(126)
        self.slider_delay3Coarse.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay3Coarse.setObjectName(_fromUtf8("slider_delay3Coarse"))
        self.horizontalLayout_3.addWidget(self.slider_delay3Coarse)
        self.slider_delay3Fine = QtGui.QSlider(self.layoutWidget4)
        self.slider_delay3Fine.setMaximum(127)
        self.slider_delay3Fine.setOrientation(QtCore.Qt.Vertical)
        self.slider_delay3Fine.setObjectName(_fromUtf8("slider_delay3Fine"))
        self.horizontalLayout_3.addWidget(self.slider_delay3Fine, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_14 = QtGui.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_3.addWidget(self.label_14)
        self.layoutWidget.raise_()
        self.btn_loop.raise_()
        self.label.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_15.raise_()
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(410, 10, 171, 281))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_18 = QtGui.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(70, 258, 31, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.layoutWidget5 = QtGui.QWidget(self.frame_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 10, 71, 241))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_pitchBase = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_pitchBase.setFont(font)
        self.label_pitchBase.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchBase.setWordWrap(False)
        self.label_pitchBase.setObjectName(_fromUtf8("label_pitchBase"))
        self.verticalLayout_21.addWidget(self.label_pitchBase)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.slider_pitchBase = QtGui.QSlider(self.layoutWidget5)
        self.slider_pitchBase.setMaximum(3)
        self.slider_pitchBase.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchBase.setObjectName(_fromUtf8("slider_pitchBase"))
        self.horizontalLayout_4.addWidget(self.slider_pitchBase)
        self.verticalLayout_21.addLayout(self.horizontalLayout_4)
        self.label_29 = QtGui.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_21.addWidget(self.label_29)
        self.layoutWidget6 = QtGui.QWidget(self.frame_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(100, 10, 71, 241))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_pitchAdjust = QtGui.QLabel(self.layoutWidget6)
        self.label_pitchAdjust.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchAdjust.setObjectName(_fromUtf8("label_pitchAdjust"))
        self.verticalLayout_20.addWidget(self.label_pitchAdjust)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.slider_pitchAdjust = QtGui.QSlider(self.layoutWidget6)
        self.slider_pitchAdjust.setEnabled(True)
        self.slider_pitchAdjust.setMaximum(127)
        self.slider_pitchAdjust.setProperty("value", 64)
        self.slider_pitchAdjust.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchAdjust.setObjectName(_fromUtf8("slider_pitchAdjust"))
        self.horizontalLayout_8.addWidget(self.slider_pitchAdjust)
        self.verticalLayout_20.addLayout(self.horizontalLayout_8)
        self.label_20 = QtGui.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_20.addWidget(self.label_20)
        self.layoutWidget7 = QtGui.QWidget(self.frame_2)
        self.layoutWidget7.setGeometry(QtCore.QRect(50, 10, 71, 241))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_pitchInterval = QtGui.QLabel(self.layoutWidget7)
        self.label_pitchInterval.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitchInterval.setObjectName(_fromUtf8("label_pitchInterval"))
        self.verticalLayout_19.addWidget(self.label_pitchInterval)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.slider_pitchInterval = QtGui.QSlider(self.layoutWidget7)
        self.slider_pitchInterval.setMaximum(36)
        self.slider_pitchInterval.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitchInterval.setObjectName(_fromUtf8("slider_pitchInterval"))
        self.horizontalLayout_7.addWidget(self.slider_pitchInterval)
        self.verticalLayout_19.addLayout(self.horizontalLayout_7)
        self.label_19 = QtGui.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_19.addWidget(self.label_19)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_18.raise_()
        self.layoutWidget.raise_()
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(590, 10, 271, 281))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.label_34 = QtGui.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(115, 258, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.layoutWidget8 = QtGui.QWidget(self.frame_3)
        self.layoutWidget8.setGeometry(QtCore.QRect(50, 10, 71, 241))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_trebleDecay = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_trebleDecay.setFont(font)
        self.label_trebleDecay.setAlignment(QtCore.Qt.AlignCenter)
        self.label_trebleDecay.setObjectName(_fromUtf8("label_trebleDecay"))
        self.verticalLayout_10.addWidget(self.label_trebleDecay)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.slider_trebleDecay = QtGui.QSlider(self.layoutWidget8)
        self.slider_trebleDecay.setMaximum(15)
        self.slider_trebleDecay.setProperty("value", 15)
        self.slider_trebleDecay.setSliderPosition(15)
        self.slider_trebleDecay.setOrientation(QtCore.Qt.Vertical)
        self.slider_trebleDecay.setObjectName(_fromUtf8("slider_trebleDecay"))
        self.horizontalLayout_12.addWidget(self.slider_trebleDecay, QtCore.Qt.AlignHCenter)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.label_35 = QtGui.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setWordWrap(True)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.verticalLayout_10.addWidget(self.label_35)
        self.layoutWidget9 = QtGui.QWidget(self.frame_3)
        self.layoutWidget9.setGeometry(QtCore.QRect(150, 10, 71, 241))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_size = QtGui.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_size.setFont(font)
        self.label_size.setAlignment(QtCore.Qt.AlignCenter)
        self.label_size.setObjectName(_fromUtf8("label_size"))
        self.verticalLayout_12.addWidget(self.label_size)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.slider_size = QtGui.QSlider(self.layoutWidget9)
        self.slider_size.setMaximum(25)
        self.slider_size.setOrientation(QtCore.Qt.Vertical)
        self.slider_size.setObjectName(_fromUtf8("slider_size"))
        self.horizontalLayout_14.addWidget(self.slider_size, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.label_23 = QtGui.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_12.addWidget(self.label_23)
        self.layoutWidget10 = QtGui.QWidget(self.frame_3)
        self.layoutWidget10.setGeometry(QtCore.QRect(200, 10, 71, 241))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.layoutWidget10)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_diffusion = QtGui.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_diffusion.setFont(font)
        self.label_diffusion.setAlignment(QtCore.Qt.AlignCenter)
        self.label_diffusion.setObjectName(_fromUtf8("label_diffusion"))
        self.verticalLayout_13.addWidget(self.label_diffusion)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.slider_diffusion = QtGui.QSlider(self.layoutWidget10)
        self.slider_diffusion.setMaximum(100)
        self.slider_diffusion.setOrientation(QtCore.Qt.Vertical)
        self.slider_diffusion.setObjectName(_fromUtf8("slider_diffusion"))
        self.horizontalLayout_15.addWidget(self.slider_diffusion, QtCore.Qt.AlignHCenter)
        self.verticalLayout_13.addLayout(self.horizontalLayout_15)
        self.label_26 = QtGui.QLabel(self.layoutWidget10)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_13.addWidget(self.label_26)
        self.layoutWidget11 = QtGui.QWidget(self.frame_3)
        self.layoutWidget11.setGeometry(QtCore.QRect(0, 10, 71, 241))
        self.layoutWidget11.setObjectName(_fromUtf8("layoutWidget11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget11)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_decayTime = QtGui.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_decayTime.setFont(font)
        self.label_decayTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_decayTime.setObjectName(_fromUtf8("label_decayTime"))
        self.verticalLayout_9.addWidget(self.label_decayTime)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.slider_decayTime = QtGui.QSlider(self.layoutWidget11)
        self.slider_decayTime.setMaximum(14)
        self.slider_decayTime.setOrientation(QtCore.Qt.Vertical)
        self.slider_decayTime.setObjectName(_fromUtf8("slider_decayTime"))
        self.horizontalLayout_11.addWidget(self.slider_decayTime, QtCore.Qt.AlignHCenter)
        self.verticalLayout_9.addLayout(self.horizontalLayout_11)
        self.label_37 = QtGui.QLabel(self.layoutWidget11)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.verticalLayout_9.addWidget(self.label_37)
        self.layoutWidget12 = QtGui.QWidget(self.frame_3)
        self.layoutWidget12.setGeometry(QtCore.QRect(100, 10, 71, 241))
        self.layoutWidget12.setObjectName(_fromUtf8("layoutWidget12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.layoutWidget12)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_bassMultiply = QtGui.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_bassMultiply.setFont(font)
        self.label_bassMultiply.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bassMultiply.setObjectName(_fromUtf8("label_bassMultiply"))
        self.verticalLayout_11.addWidget(self.label_bassMultiply)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.slider_bassMultiply = QtGui.QSlider(self.layoutWidget12)
        self.slider_bassMultiply.setMaximum(31)
        self.slider_bassMultiply.setOrientation(QtCore.Qt.Vertical)
        self.slider_bassMultiply.setObjectName(_fromUtf8("slider_bassMultiply"))
        self.horizontalLayout_13.addWidget(self.slider_bassMultiply)
        self.verticalLayout_11.addLayout(self.horizontalLayout_13)
        self.label_38 = QtGui.QLabel(self.layoutWidget12)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.verticalLayout_11.addWidget(self.label_38)
        self.frame_5 = QtGui.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(590, 300, 271, 281))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.label_50 = QtGui.QLabel(self.frame_5)
        self.label_50.setGeometry(QtCore.QRect(110, 257, 51, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.layoutWidget13 = QtGui.QWidget(self.frame_5)
        self.layoutWidget13.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.layoutWidget13.setObjectName(_fromUtf8("layoutWidget13"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.layoutWidget13)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_reverbBalance = QtGui.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_reverbBalance.setFont(font)
        self.label_reverbBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reverbBalance.setObjectName(_fromUtf8("label_reverbBalance"))
        self.verticalLayout_8.addWidget(self.label_reverbBalance)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.slider_reverbBalance = QtGui.QSlider(self.layoutWidget13)
        self.slider_reverbBalance.setMaximum(127)
        self.slider_reverbBalance.setProperty("value", 63)
        self.slider_reverbBalance.setOrientation(QtCore.Qt.Vertical)
        self.slider_reverbBalance.setObjectName(_fromUtf8("slider_reverbBalance"))
        self.horizontalLayout_18.addWidget(self.slider_reverbBalance)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.label_reverbBalance_2 = QtGui.QLabel(self.layoutWidget13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_reverbBalance_2.setFont(font)
        self.label_reverbBalance_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_reverbBalance_2.setWordWrap(True)
        self.label_reverbBalance_2.setObjectName(_fromUtf8("label_reverbBalance_2"))
        self.verticalLayout_8.addWidget(self.label_reverbBalance_2)
        self.layoutWidget14 = QtGui.QWidget(self.frame_5)
        self.layoutWidget14.setGeometry(QtCore.QRect(60, 10, 71, 241))
        self.layoutWidget14.setObjectName(_fromUtf8("layoutWidget14"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.layoutWidget14)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_outputBalance = QtGui.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_outputBalance.setFont(font)
        self.label_outputBalance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputBalance.setObjectName(_fromUtf8("label_outputBalance"))
        self.verticalLayout_14.addWidget(self.label_outputBalance)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.slider_outputBalance = QtGui.QSlider(self.layoutWidget14)
        self.slider_outputBalance.setMaximum(127)
        self.slider_outputBalance.setProperty("value", 63)
        self.slider_outputBalance.setOrientation(QtCore.Qt.Vertical)
        self.slider_outputBalance.setObjectName(_fromUtf8("slider_outputBalance"))
        self.horizontalLayout_19.addWidget(self.slider_outputBalance)
        self.verticalLayout_14.addLayout(self.horizontalLayout_19)
        self.label_30 = QtGui.QLabel(self.layoutWidget14)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_14.addWidget(self.label_30)
        self.layoutWidget15 = QtGui.QWidget(self.frame_5)
        self.layoutWidget15.setGeometry(QtCore.QRect(110, 10, 71, 241))
        self.layoutWidget15.setObjectName(_fromUtf8("layoutWidget15"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.layoutWidget15)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_outputLevel = QtGui.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_outputLevel.setFont(font)
        self.label_outputLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_outputLevel.setObjectName(_fromUtf8("label_outputLevel"))
        self.verticalLayout_22.addWidget(self.label_outputLevel)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.slider_outputLevel = QtGui.QSlider(self.layoutWidget15)
        self.slider_outputLevel.setMaximum(127)
        self.slider_outputLevel.setProperty("value", 127)
        self.slider_outputLevel.setOrientation(QtCore.Qt.Vertical)
        self.slider_outputLevel.setObjectName(_fromUtf8("slider_outputLevel"))
        self.horizontalLayout_21.addWidget(self.slider_outputLevel)
        self.verticalLayout_22.addLayout(self.horizontalLayout_21)
        self.label_31 = QtGui.QLabel(self.layoutWidget15)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_22.addWidget(self.label_31)
        self.layoutWidget16 = QtGui.QWidget(self.frame_5)
        self.layoutWidget16.setGeometry(QtCore.QRect(160, 10, 81, 241))
        self.layoutWidget16.setObjectName(_fromUtf8("layoutWidget16"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.layoutWidget16)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_inputLevel = QtGui.QLabel(self.layoutWidget16)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_inputLevel.setFont(font)
        self.label_inputLevel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_inputLevel.setObjectName(_fromUtf8("label_inputLevel"))
        self.verticalLayout_23.addWidget(self.label_inputLevel)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.slider_inputLevel = QtGui.QSlider(self.layoutWidget16)
        self.slider_inputLevel.setMaximum(127)
        self.slider_inputLevel.setProperty("value", 127)
        self.slider_inputLevel.setOrientation(QtCore.Qt.Vertical)
        self.slider_inputLevel.setObjectName(_fromUtf8("slider_inputLevel"))
        self.horizontalLayout_22.addWidget(self.slider_inputLevel)
        self.verticalLayout_23.addLayout(self.horizontalLayout_22)
        self.label_32 = QtGui.QLabel(self.layoutWidget16)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setWordWrap(True)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_23.addWidget(self.label_32)
        self.frame_4 = QtGui.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(440, 300, 141, 281))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.layoutWidget17 = QtGui.QWidget(self.frame_4)
        self.layoutWidget17.setGeometry(QtCore.QRect(60, 10, 71, 241))
        self.layoutWidget17.setObjectName(_fromUtf8("layoutWidget17"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget17)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_lowCutFilter = QtGui.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_lowCutFilter.setFont(font)
        self.label_lowCutFilter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lowCutFilter.setObjectName(_fromUtf8("label_lowCutFilter"))
        self.verticalLayout_7.addWidget(self.label_lowCutFilter)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.slider_lowCutFilter = QtGui.QSlider(self.layoutWidget17)
        self.slider_lowCutFilter.setMaximum(31)
        self.slider_lowCutFilter.setOrientation(QtCore.Qt.Vertical)
        self.slider_lowCutFilter.setObjectName(_fromUtf8("slider_lowCutFilter"))
        self.horizontalLayout_17.addWidget(self.slider_lowCutFilter)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.label_28 = QtGui.QLabel(self.layoutWidget17)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(True)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_7.addWidget(self.label_28)
        self.layoutWidget18 = QtGui.QWidget(self.frame_4)
        self.layoutWidget18.setGeometry(QtCore.QRect(10, 10, 71, 241))
        self.layoutWidget18.setObjectName(_fromUtf8("layoutWidget18"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget18)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_highCutFilter = QtGui.QLabel(self.layoutWidget18)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_highCutFilter.setFont(font)
        self.label_highCutFilter.setAlignment(QtCore.Qt.AlignCenter)
        self.label_highCutFilter.setObjectName(_fromUtf8("label_highCutFilter"))
        self.verticalLayout_6.addWidget(self.label_highCutFilter)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.slider_highCutFilter = QtGui.QSlider(self.layoutWidget18)
        self.slider_highCutFilter.setMaximum(15)
        self.slider_highCutFilter.setProperty("value", 15)
        self.slider_highCutFilter.setOrientation(QtCore.Qt.Vertical)
        self.slider_highCutFilter.setObjectName(_fromUtf8("slider_highCutFilter"))
        self.horizontalLayout_16.addWidget(self.slider_highCutFilter)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.label_27 = QtGui.QLabel(self.layoutWidget18)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setWordWrap(True)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_6.addWidget(self.label_27)
        self.label_51 = QtGui.QLabel(self.frame_4)
        self.label_51.setGeometry(QtCore.QRect(40, 257, 81, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.layoutWidget_7 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_7.setGeometry(QtCore.QRect(10, 463, 301, 51))
        self.layoutWidget_7.setObjectName(_fromUtf8("layoutWidget_7"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.slider_LFORate = QtGui.QSlider(self.layoutWidget_7)
        self.slider_LFORate.setMaximum(127)
        self.slider_LFORate.setOrientation(QtCore.Qt.Horizontal)
        self.slider_LFORate.setObjectName(_fromUtf8("slider_LFORate"))
        self.verticalLayout_29.addWidget(self.slider_LFORate)
        self.label_36 = QtGui.QLabel(self.layoutWidget_7)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.verticalLayout_29.addWidget(self.label_36, QtCore.Qt.AlignLeft)
        self.horizontalLayout_28.addLayout(self.verticalLayout_29)
        self.layoutWidget_8 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget_8.setGeometry(QtCore.QRect(10, 523, 201, 71))
        self.layoutWidget_8.setObjectName(_fromUtf8("layoutWidget_8"))
        self.verticalLayout_33 = QtGui.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_33.setObjectName(_fromUtf8("verticalLayout_33"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        self.spinbox_midiChannel = QtGui.QSpinBox(self.layoutWidget_8)
        self.spinbox_midiChannel.setMinimum(1)
        self.spinbox_midiChannel.setMaximum(16)
        self.spinbox_midiChannel.setObjectName(_fromUtf8("spinbox_midiChannel"))
        self.horizontalLayout_32.addWidget(self.spinbox_midiChannel, QtCore.Qt.AlignLeft)
        self.comboBox_midiPort = QtGui.QComboBox(self.layoutWidget_8)
        self.comboBox_midiPort.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboBox_midiPort.setObjectName(_fromUtf8("comboBox_midiPort"))
        self.horizontalLayout_32.addWidget(self.comboBox_midiPort)
        self.verticalLayout_33.addLayout(self.horizontalLayout_32)
        self.label_39 = QtGui.QLabel(self.layoutWidget_8)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.verticalLayout_33.addWidget(self.label_39)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(280, 463, 91, 51))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_LFORateHz = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_LFORateHz.setFont(font)
        self.label_LFORateHz.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_LFORateHz.setObjectName(_fromUtf8("label_LFORateHz"))
        self.verticalLayout_15.addWidget(self.label_LFORateHz)
        self.label_LFORateBPM = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Noto Sans"))
        font.setBold(False)
        font.setWeight(50)
        self.label_LFORateBPM.setFont(font)
        self.label_LFORateBPM.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_LFORateBPM.setObjectName(_fromUtf8("label_LFORateBPM"))
        self.verticalLayout_15.addWidget(self.label_LFORateBPM)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(0, 300, 431, 131))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.dial_patch2Threshold = QtGui.QDial(self.widget1)
        self.dial_patch2Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch2Threshold.setFont(font)
        self.dial_patch2Threshold.setMaximum(127)
        self.dial_patch2Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch2Threshold.setObjectName(_fromUtf8("dial_patch2Threshold"))
        self.horizontalLayout_10.addWidget(self.dial_patch2Threshold)
        self.dial_patch2ScaleFactor = QtGui.QDial(self.widget1)
        self.dial_patch2ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch2ScaleFactor.setFont(font)
        self.dial_patch2ScaleFactor.setMinimum(-64)
        self.dial_patch2ScaleFactor.setMaximum(63)
        self.dial_patch2ScaleFactor.setProperty("value", 0)
        self.dial_patch2ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch2ScaleFactor.setObjectName(_fromUtf8("dial_patch2ScaleFactor"))
        self.horizontalLayout_10.addWidget(self.dial_patch2ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_10, 3, 6, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.dial_patch4Threshold = QtGui.QDial(self.widget1)
        self.dial_patch4Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch4Threshold.setFont(font)
        self.dial_patch4Threshold.setMaximum(127)
        self.dial_patch4Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch4Threshold.setObjectName(_fromUtf8("dial_patch4Threshold"))
        self.horizontalLayout_23.addWidget(self.dial_patch4Threshold)
        self.dial_patch4ScaleFactor = QtGui.QDial(self.widget1)
        self.dial_patch4ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch4ScaleFactor.setFont(font)
        self.dial_patch4ScaleFactor.setMinimum(-64)
        self.dial_patch4ScaleFactor.setMaximum(63)
        self.dial_patch4ScaleFactor.setProperty("value", 0)
        self.dial_patch4ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch4ScaleFactor.setObjectName(_fromUtf8("dial_patch4ScaleFactor"))
        self.horizontalLayout_23.addWidget(self.dial_patch4ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_23, 3, 10, 1, 1)
        self.comboBox_patch4Destination = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch4Destination.setFont(font)
        self.comboBox_patch4Destination.setObjectName(_fromUtf8("comboBox_patch4Destination"))
        self.gridLayout.addWidget(self.comboBox_patch4Destination, 2, 10, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.comboBox_patch2Destination = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch2Destination.setFont(font)
        self.comboBox_patch2Destination.setObjectName(_fromUtf8("comboBox_patch2Destination"))
        self.gridLayout.addWidget(self.comboBox_patch2Destination, 2, 6, 1, 1)
        self.comboBox_patch3Destination = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch3Destination.setFont(font)
        self.comboBox_patch3Destination.setObjectName(_fromUtf8("comboBox_patch3Destination"))
        self.gridLayout.addWidget(self.comboBox_patch3Destination, 2, 8, 1, 1)
        self.comboBox_patch1Destination = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch1Destination.setFont(font)
        self.comboBox_patch1Destination.setObjectName(_fromUtf8("comboBox_patch1Destination"))
        self.gridLayout.addWidget(self.comboBox_patch1Destination, 2, 3, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.dial_patch3Threshold = QtGui.QDial(self.widget1)
        self.dial_patch3Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch3Threshold.setFont(font)
        self.dial_patch3Threshold.setMaximum(127)
        self.dial_patch3Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch3Threshold.setObjectName(_fromUtf8("dial_patch3Threshold"))
        self.horizontalLayout_20.addWidget(self.dial_patch3Threshold)
        self.dial_patch3ScaleFactor = QtGui.QDial(self.widget1)
        self.dial_patch3ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch3ScaleFactor.setFont(font)
        self.dial_patch3ScaleFactor.setMinimum(-64)
        self.dial_patch3ScaleFactor.setMaximum(63)
        self.dial_patch3ScaleFactor.setProperty("value", 0)
        self.dial_patch3ScaleFactor.setOrientation(QtCore.Qt.Vertical)
        self.dial_patch3ScaleFactor.setObjectName(_fromUtf8("dial_patch3ScaleFactor"))
        self.horizontalLayout_20.addWidget(self.dial_patch3ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_20, 3, 8, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.dial_patch1Threshold = QtGui.QDial(self.widget1)
        self.dial_patch1Threshold.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch1Threshold.setFont(font)
        self.dial_patch1Threshold.setMaximum(127)
        self.dial_patch1Threshold.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch1Threshold.setObjectName(_fromUtf8("dial_patch1Threshold"))
        self.horizontalLayout_9.addWidget(self.dial_patch1Threshold)
        self.dial_patch1ScaleFactor = QtGui.QDial(self.widget1)
        self.dial_patch1ScaleFactor.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(4)
        self.dial_patch1ScaleFactor.setFont(font)
        self.dial_patch1ScaleFactor.setMinimum(-64)
        self.dial_patch1ScaleFactor.setMaximum(63)
        self.dial_patch1ScaleFactor.setProperty("value", 0)
        self.dial_patch1ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.dial_patch1ScaleFactor.setObjectName(_fromUtf8("dial_patch1ScaleFactor"))
        self.horizontalLayout_9.addWidget(self.dial_patch1ScaleFactor)
        self.gridLayout.addLayout(self.horizontalLayout_9, 3, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.comboBox_patch2Source = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch2Source.setFont(font)
        self.comboBox_patch2Source.setObjectName(_fromUtf8("comboBox_patch2Source"))
        self.gridLayout.addWidget(self.comboBox_patch2Source, 1, 6, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 10, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.comboBox_patch1Source = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch1Source.setFont(font)
        self.comboBox_patch1Source.setObjectName(_fromUtf8("comboBox_patch1Source"))
        self.gridLayout.addWidget(self.comboBox_patch1Source, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_patch3Source = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch3Source.setFont(font)
        self.comboBox_patch3Source.setObjectName(_fromUtf8("comboBox_patch3Source"))
        self.gridLayout.addWidget(self.comboBox_patch3Source, 1, 8, 1, 1)
        self.comboBox_patch4Source = QtGui.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_patch4Source.setFont(font)
        self.comboBox_patch4Source.setObjectName(_fromUtf8("comboBox_patch4Source"))
        self.gridLayout.addWidget(self.comboBox_patch4Source, 1, 10, 1, 1)
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.frame_5.raise_()
        self.frame.raise_()
        self.frame_4.raise_()
        self.layoutWidget_7.raise_()
        self.layoutWidget_8.raise_()
        self.label_LFORateBPM.raise_()
        self.label_LFORateHz.raise_()
        self.comboBox_patch1Source.raise_()
        self.comboBox_patch2Source.raise_()
        self.comboBox_patch3Source.raise_()
        self.comboBox_patch4Source.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.dial_patch1ScaleFactor.raise_()
        self.dial_patch1Threshold.raise_()
        self.dial_patch2ScaleFactor.raise_()
        self.dial_patch2Threshold.raise_()
        self.dial_patch3Threshold.raise_()
        self.dial_patch3ScaleFactor.raise_()
        self.dial_patch4Threshold.raise_()
        self.dial_patch4ScaleFactor.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Lexicon LXP-5 Editor", None))
        self.label_15.setText(_translate("MainWindow", "Feedback", None))
        self.btn_loop.setText(_translate("MainWindow", "Loop", None))
        self.label.setText(_translate("MainWindow", "Delay", None))
        self.label_delay2Time.setText(_translate("MainWindow", "0.0 ms", None))
        self.label_11.setText(_translate("MainWindow", "Delay 2<br>Time", None))
        self.label_delay1Time.setText(_translate("MainWindow", "0.0 ms", None))
        self.label_8.setText(_translate("MainWindow", "Delay 1<br>Time", None))
        self.label_feedback1.setText(_translate("MainWindow", "0.0%", None))
        self.label_10.setText(_translate("MainWindow", "Amt 1<br>", None))
        self.label_feedback2.setText(_translate("MainWindow", "0.0%", None))
        self.label_12.setText(_translate("MainWindow", "Amt 2<br>", None))
        self.label_delay3Time.setText(_translate("MainWindow", "0.0 ms", None))
        self.label_14.setText(_translate("MainWindow", "Delay 3<br>Time", None))
        self.label_18.setText(_translate("MainWindow", "Pitch", None))
        self.label_pitchBase.setText(_translate("MainWindow", "Defeat", None))
        self.label_29.setText(_translate("MainWindow", "Base<br>", None))
        self.label_pitchAdjust.setText(_translate("MainWindow", "+0", None))
        self.label_20.setText(_translate("MainWindow", "Adjust<br>", None))
        self.label_pitchInterval.setText(_translate("MainWindow", "+0 st", None))
        self.label_19.setText(_translate("MainWindow", "Interval<br>", None))
        self.label_34.setText(_translate("MainWindow", "Reverb", None))
        self.label_trebleDecay.setText(_translate("MainWindow", "Full", None))
        self.label_35.setText(_translate("MainWindow", "Treble<br>Decay", None))
        self.label_size.setText(_translate("MainWindow", "8.0 m", None))
        self.label_23.setText(_translate("MainWindow", "Size<br>", None))
        self.label_diffusion.setText(_translate("MainWindow", "0.0%", None))
        self.label_26.setText(_translate("MainWindow", "Diffusion<br>", None))
        self.label_decayTime.setText(_translate("MainWindow", "0.5 sec", None))
        self.label_37.setText(_translate("MainWindow", "Decay<br>", None))
        self.label_bassMultiply.setText(_translate("MainWindow", "x0.30", None))
        self.label_38.setText(_translate("MainWindow", "Bass<br>Multiply", None))
        self.label_50.setText(_translate("MainWindow", "Levels", None))
        self.label_reverbBalance.setText(_translate("MainWindow", "0", None))
        self.label_reverbBalance_2.setText(_translate("MainWindow", "Reverb<br>Balance", None))
        self.label_outputBalance.setText(_translate("MainWindow", "0", None))
        self.label_30.setText(_translate("MainWindow", "Output<br>Balance", None))
        self.label_outputLevel.setText(_translate("MainWindow", "100%", None))
        self.label_31.setText(_translate("MainWindow", "Output<br>Level", None))
        self.label_inputLevel.setText(_translate("MainWindow", "100%", None))
        self.label_32.setText(_translate("MainWindow", "Input<br>Level", None))
        self.label_lowCutFilter.setText(_translate("MainWindow", "Full", None))
        self.label_28.setText(_translate("MainWindow", "Low<br>Cut", None))
        self.label_highCutFilter.setText(_translate("MainWindow", "Full", None))
        self.label_27.setText(_translate("MainWindow", "High<br>Cut", None))
        self.label_51.setText(_translate("MainWindow", "Equalization", None))
        self.label_36.setText(_translate("MainWindow", "LFO Rate", None))
        self.label_39.setText(_translate("MainWindow", "MIDI Channel", None))
        self.label_LFORateHz.setText(_translate("MainWindow", "0.066 Hz", None))
        self.label_LFORateBPM.setText(_translate("MainWindow", "3.96 bpm", None))
        self.dial_patch2Threshold.setToolTip(_translate("MainWindow", "Patch 2 Threshold", None))
        self.dial_patch2ScaleFactor.setToolTip(_translate("MainWindow", "Patch 2 Scale Factor", None))
        self.dial_patch4Threshold.setToolTip(_translate("MainWindow", "Patch 4 Threshold", None))
        self.dial_patch4ScaleFactor.setToolTip(_translate("MainWindow", "Patch 4 Scale Factor", None))
        self.label_9.setText(_translate("MainWindow", "Destination", None))
        self.dial_patch3Threshold.setToolTip(_translate("MainWindow", "Patch 3 Threshold", None))
        self.dial_patch3ScaleFactor.setToolTip(_translate("MainWindow", "Patch 3 Scale Factor", None))
        self.dial_patch1Threshold.setToolTip(_translate("MainWindow", "Patch 1 Threshold", None))
        self.dial_patch1ScaleFactor.setToolTip(_translate("MainWindow", "Patch 1 Scale Factor", None))
        self.label_7.setText(_translate("MainWindow", "Threshold/<br>Scale Factor", None))
        self.label_4.setText(_translate("MainWindow", "Patch 3", None))
        self.label_2.setText(_translate("MainWindow", "Patch 1", None))
        self.label_5.setText(_translate("MainWindow", "Patch 4", None))
        self.label_3.setText(_translate("MainWindow", "Patch 2", None))
        self.label_6.setText(_translate("MainWindow", "Source", None))

